on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.21'

      - name: Go Version
        run: go version

      - name: Go Mod Init
        run: go mod init ecfmp

      - name: Install Go Proto Packages
        run: go get -u google.golang.org/protobuf/cmd/protoc-gen-go google.golang.org/grpc/cmd/protoc-gen-go-grpc

      - name: Install Protoc
        uses: arduino/setup-protoc@v2

      - name: Build Discord
        run: make discord_proto

      - name: Build Health
        run: make health_proto
