on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.21'

      - name: Go Version
        run: go version

      - name: Go Mod Init
        run: go mod init ecfmp

      - name: Add Go to PATH
        run: echo "/home/runner/go/bin" >> $GITHUB_PATH

      - name: Install Go Proto Packages
        run: |
          go get google.golang.org/protobuf/cmd/protoc-gen-go
          go get google.golang.org/grpc/cmd/protoc-gen-go-grpc
          go list -m all
          ls -l $(go env GOPATH)/bin

      - name: Install Protoc
        uses: arduino/setup-protoc@v2

      - name: Build Discord
        run: make discord_proto

      - name: Build Health
        run: make health_proto
